"""Add ContactDiary model

Revision ID: 0100b609ccb2
Revises: 66a3a8b9223b
Create Date: 2026-03-03 15:22:38.431330

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0100b609ccb2"
down_revision: Union[str, Sequence[str], None] = "66a3a8b9223b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact_diaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("office_department", sa.String(), nullable=False),
        sa.Column("contact_person", sa.String(), nullable=False),
        sa.Column("designation", sa.String(), nullable=True),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("email_address", sa.String(), nullable=True),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contact_diaries_contact_person"),
        "contact_diaries",
        ["contact_person"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contact_diaries_designation"),
        "contact_diaries",
        ["designation"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contact_diaries_id"), "contact_diaries", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_contact_diaries_office_department"),
        "contact_diaries",
        ["office_department"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contact_diaries_status"), "contact_diaries", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_contact_diaries_status"), table_name="contact_diaries")
    op.drop_index(
        op.f("ix_contact_diaries_office_department"), table_name="contact_diaries"
    )
    op.drop_index(op.f("ix_contact_diaries_id"), table_name="contact_diaries")
    op.drop_index(op.f("ix_contact_diaries_designation"), table_name="contact_diaries")
    op.drop_index(
        op.f("ix_contact_diaries_contact_person"), table_name="contact_diaries"
    )
    op.drop_table("contact_diaries")
    # ### end Alembic commands ###
