"""Complete Application Model

Revision ID: 0b12d88ab0c3
Revises: 4867a7dc9b30
Create Date: 2026-01-31 13:54:26.906844

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0b12d88ab0c3"
down_revision: Union[str, Sequence[str], None] = "4867a7dc9b30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Enums
    property_usage_enum = sa.Enum(
        "DOMESTIC", "COMMERCIAL", "HOTEL", name="propertyusagetype"
    )
    property_usage_enum.create(op.get_bind())

    department_enum = sa.Enum("ULB", name="departmenttype")
    department_enum.create(op.get_bind())

    op.add_column(
        "applications",
        sa.Column(
            "applicant_name",
            sa.String(),
            nullable=False,
            server_default="Temp Applicant",
        ),
    )
    op.add_column(
        "applications",
        sa.Column(
            "father_name", sa.String(), nullable=False, server_default="Temp Father"
        ),
    )
    op.add_column(
        "applications",
        sa.Column("mobile", sa.String(), nullable=False, server_default="0000000000"),
    )
    op.add_column("applications", sa.Column("email", sa.String(), nullable=True))
    op.add_column(
        "applications",
        sa.Column(
            "current_address",
            sa.String(),
            nullable=False,
            server_default="Temp Address",
        ),
    )
    op.add_column(
        "applications",
        sa.Column(
            "property_address",
            sa.String(),
            nullable=False,
            server_default="Temp Property Address",
        ),
    )
    op.add_column(
        "applications",
        sa.Column(
            "work_description", sa.String(), nullable=False, server_default="Temp Work"
        ),
    )
    op.add_column(
        "applications", sa.Column("contractor_name", sa.String(), nullable=True)
    )
    op.add_column(
        "applications",
        sa.Column(
            "is_agriculture_land", sa.Boolean(), nullable=False, server_default="false"
        ),
    )
    op.add_column(
        "applications",
        sa.Column(
            "property_usage",
            sa.Enum("DOMESTIC", "COMMERCIAL", "HOTEL", name="propertyusagetype"),
            nullable=False,
            server_default="DOMESTIC",
        ),
    )
    op.add_column(
        "applications",
        sa.Column(
            "department",
            sa.Enum("ULB", name="departmenttype"),
            nullable=False,
            server_default="ULB",
        ),
    )
    op.add_column(
        "applications",
        sa.Column("ward_zone", sa.String(), nullable=False, server_default="Unknown"),
    )
    op.create_index(
        op.f("ix_applications_applicant_name"),
        "applications",
        ["applicant_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_applications_mobile"), "applications", ["mobile"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_applications_mobile"), table_name="applications")
    op.drop_index(op.f("ix_applications_applicant_name"), table_name="applications")
    op.drop_column("applications", "ward_zone")
    op.drop_column("applications", "department")
    op.drop_column("applications", "property_usage")
    op.drop_column("applications", "is_agriculture_land")
    op.drop_column("applications", "contractor_name")
    op.drop_column("applications", "work_description")
    op.drop_column("applications", "property_address")
    op.drop_column("applications", "current_address")
    op.drop_column("applications", "email")
    op.drop_column("applications", "mobile")
    op.drop_column("applications", "father_name")
    op.drop_column("applications", "applicant_name")
    # ### end Alembic commands ###
    # Drop Enums
    op.execute("DROP TYPE propertyusagetype")
    op.execute("DROP TYPE departmenttype")
