"""add_media_fields_to_tenders_events_leaders_notices

Revision ID: 0ddbf653aea1
Revises: e81dac610a5f
Create Date: 2026-04-28 14:32:06.336726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ddbf653aea1'
down_revision: Union[str, Sequence[str], None] = 'e81dac610a5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('image_path', sa.String(), nullable=True))
    op.add_column('leaders', sa.Column('image_path', sa.String(), nullable=True))
    op.add_column('notices', sa.Column('image_path', sa.String(), nullable=True))
    op.add_column('notices', sa.Column('document_path', sa.String(), nullable=True))
    op.add_column('tenders', sa.Column('document_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenders', 'document_path')
    op.drop_column('notices', 'document_path')
    op.drop_column('notices', 'image_path')
    op.drop_column('leaders', 'image_path')
    op.drop_column('events', 'image_path')
    # ### end Alembic commands ###
