"""change_vehicle_entry_media_to_json

Revision ID: 32f70822c006
Revises: 917c2741a3d7
Create Date: 2026-04-21 11:20:24.612457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32f70822c006'
down_revision: Union[str, Sequence[str], None] = '917c2741a3d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_entries', sa.Column('media', sa.JSON(), nullable=True))
    op.drop_column('vehicle_entries', 'media_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_entries', sa.Column('media_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('vehicle_entries', 'media')
    # ### end Alembic commands ###
