"""add_complaint_assignment_fields

Revision ID: 3a3673c22af3
Revises: 7e0469837c7f
Create Date: 2026-04-15 00:55:50.864053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a3673c22af3'
down_revision: Union[str, Sequence[str], None] = '7e0469837c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('assigned_to_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_complaints_assigned_to_id'), 'complaints', ['assigned_to_id'], unique=False)
    op.create_foreign_key(None, 'complaints', 'users', ['assigned_to_id'], ['id'])
    op.add_column('departments', sa.Column('jen_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'departments', 'users', ['jen_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'jen_id')
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_index(op.f('ix_complaints_assigned_to_id'), table_name='complaints')
    op.drop_column('complaints', 'assigned_to_id')
    # ### end Alembic commands ###
