"""add fields to event notice and leader

Revision ID: 3a6132de64b5
Revises: d42b869e3ab1
Create Date: 2026-05-08 11:19:22.384757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a6132de64b5'
down_revision: Union[str, Sequence[str], None] = 'd42b869e3ab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('description', sa.String(), nullable=True))
    op.add_column('leaders', sa.Column('message', sa.String(), nullable=True))
    op.add_column('notices', sa.Column('content', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notices', 'content')
    op.drop_column('leaders', 'message')
    op.drop_column('events', 'description')
    # ### end Alembic commands ###
