"""add_workflow_models

Revision ID: 3b2b4d33e972
Revises: cb513640f036
Create Date: 2026-02-10 16:42:44.787110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '3b2b4d33e972'
down_revision: Union[str, Sequence[str], None] = 'cb513640f036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ── Add new values to existing enum types ───────────────────────────────
    op.execute(sa.text("ALTER TYPE applicationstatus ADD VALUE IF NOT EXISTS 'FORWARDED'"))
    op.execute(sa.text("ALTER TYPE applicationstatus ADD VALUE IF NOT EXISTS 'TOKEN_GENERATED'"))
    op.execute(sa.text("ALTER TYPE applicationphasestatus ADD VALUE IF NOT EXISTS 'ACTIVE'"))
    op.execute(sa.text("ALTER TYPE applicationdocumenttype ADD VALUE IF NOT EXISTS 'SITE_INSPECTION'"))
    op.execute(sa.text("ALTER TYPE applicationdocumenttype ADD VALUE IF NOT EXISTS 'GEO_TAGGED_PHOTO'"))

    # ── Create new enum types ───────────────────────────────────────────────
    workflowaction_enum = postgresql.ENUM(
        'APPROVE', 'REJECT', 'OBJECT', 'FORWARD', 'GENERATE_TOKENS',
        name='workflowaction', create_type=False,
    )
    workflowaction_enum.create(op.get_bind(), checkfirst=True)

    commenttype_enum = postgresql.ENUM(
        'GENERAL', 'DEPT_REVIEW', 'OBJECTION_RESPONSE', 'INSPECTION_REMARK',
        name='commenttype', create_type=False,
    )
    commenttype_enum.create(op.get_bind(), checkfirst=True)

    # ── Enum column references (never re-create the type) ───────────────────
    workflowaction_col = postgresql.ENUM(
        'APPROVE', 'REJECT', 'OBJECT', 'FORWARD', 'GENERATE_TOKENS',
        name='workflowaction', create_type=False,
    )
    applicationstatus_col = postgresql.ENUM(
        'PENDING', 'SUBMITTED', 'APPROVED', 'FORWARDED', 'WITHHELD',
        'OBJECTED', 'REJECTED', 'TOKEN_GENERATED',
        name='applicationstatus', create_type=False,
    )
    commenttype_col = postgresql.ENUM(
        'GENERAL', 'DEPT_REVIEW', 'OBJECTION_RESPONSE', 'INSPECTION_REMARK',
        name='commenttype', create_type=False,
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('action', workflowaction_col, nullable=False),
    sa.Column('from_status', applicationstatus_col, nullable=False),
    sa.Column('to_status', applicationstatus_col, nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=False),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('phase', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_action_logs_action'), 'application_action_logs', ['action'], unique=False)
    op.create_index(op.f('ix_application_action_logs_application_id'), 'application_action_logs', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_action_logs_id'), 'application_action_logs', ['id'], unique=False)
    op.create_index(op.f('ix_application_action_logs_performed_at'), 'application_action_logs', ['performed_at'], unique=False)
    op.create_index(op.f('ix_application_action_logs_performed_by'), 'application_action_logs', ['performed_by'], unique=False)
    op.create_table('inspection_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('inspected_by', sa.Integer(), nullable=False),
    sa.Column('inspected_at', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=False),
    sa.Column('media_paths', sa.JSON(), nullable=True),
    sa.Column('recommended_phases', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['inspected_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_reports_application_id'), 'inspection_reports', ['application_id'], unique=False)
    op.create_index(op.f('ix_inspection_reports_id'), 'inspection_reports', ['id'], unique=False)
    op.create_index(op.f('ix_inspection_reports_inspected_at'), 'inspection_reports', ['inspected_at'], unique=False)
    op.create_index(op.f('ix_inspection_reports_inspected_by'), 'inspection_reports', ['inspected_by'], unique=False)
    op.create_table('naka_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity_brought', sa.Integer(), nullable=False),
    sa.Column('entry_by', sa.Integer(), nullable=False),
    sa.Column('entry_at', sa.DateTime(), nullable=False),
    sa.Column('vehicle_number', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('media_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['entry_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_naka_entries_application_id'), 'naka_entries', ['application_id'], unique=False)
    op.create_index(op.f('ix_naka_entries_entry_at'), 'naka_entries', ['entry_at'], unique=False)
    op.create_index(op.f('ix_naka_entries_entry_by'), 'naka_entries', ['entry_by'], unique=False)
    op.create_index(op.f('ix_naka_entries_id'), 'naka_entries', ['id'], unique=False)
    op.create_index(op.f('ix_naka_entries_material_id'), 'naka_entries', ['material_id'], unique=False)
    op.create_index(op.f('ix_naka_entries_phase'), 'naka_entries', ['phase'], unique=False)
    op.add_column('application_approvals', sa.Column('action', workflowaction_col, nullable=True))
    op.add_column('application_approvals', sa.Column('remarks', sa.String(), nullable=True))
    op.create_index(op.f('ix_application_approvals_action'), 'application_approvals', ['action'], unique=False)
    op.add_column('application_comments', sa.Column('comment_type', commenttype_col, nullable=True))
    op.add_column('application_comments', sa.Column('media_paths', sa.JSON(), nullable=True))
    op.add_column('application_comments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_application_comments_comment_type'), 'application_comments', ['comment_type'], unique=False)
    op.create_index(op.f('ix_application_comments_created_at'), 'application_comments', ['created_at'], unique=False)
    op.create_foreign_key(None, 'application_phase_materials', 'materials', ['material_id'], ['id'])
    op.add_column('application_phases', sa.Column('activated_at', sa.DateTime(), nullable=True))
    op.add_column('application_phases', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_phases', 'completed_at')
    op.drop_column('application_phases', 'activated_at')
    op.drop_constraint(None, 'application_phase_materials', type_='foreignkey')
    op.drop_index(op.f('ix_application_comments_created_at'), table_name='application_comments')
    op.drop_index(op.f('ix_application_comments_comment_type'), table_name='application_comments')
    op.drop_column('application_comments', 'created_at')
    op.drop_column('application_comments', 'media_paths')
    op.drop_column('application_comments', 'comment_type')
    op.drop_index(op.f('ix_application_approvals_action'), table_name='application_approvals')
    op.drop_column('application_approvals', 'remarks')
    op.drop_column('application_approvals', 'action')
    op.drop_index(op.f('ix_naka_entries_phase'), table_name='naka_entries')
    op.drop_index(op.f('ix_naka_entries_material_id'), table_name='naka_entries')
    op.drop_index(op.f('ix_naka_entries_id'), table_name='naka_entries')
    op.drop_index(op.f('ix_naka_entries_entry_by'), table_name='naka_entries')
    op.drop_index(op.f('ix_naka_entries_entry_at'), table_name='naka_entries')
    op.drop_index(op.f('ix_naka_entries_application_id'), table_name='naka_entries')
    op.drop_table('naka_entries')
    op.drop_index(op.f('ix_inspection_reports_inspected_by'), table_name='inspection_reports')
    op.drop_index(op.f('ix_inspection_reports_inspected_at'), table_name='inspection_reports')
    op.drop_index(op.f('ix_inspection_reports_id'), table_name='inspection_reports')
    op.drop_index(op.f('ix_inspection_reports_application_id'), table_name='inspection_reports')
    op.drop_table('inspection_reports')
    op.drop_index(op.f('ix_application_action_logs_performed_by'), table_name='application_action_logs')
    op.drop_index(op.f('ix_application_action_logs_performed_at'), table_name='application_action_logs')
    op.drop_index(op.f('ix_application_action_logs_id'), table_name='application_action_logs')
    op.drop_index(op.f('ix_application_action_logs_application_id'), table_name='application_action_logs')
    op.drop_index(op.f('ix_application_action_logs_action'), table_name='application_action_logs')
    op.drop_table('application_action_logs')
    # ### end Alembic commands ###
