"""add_material_foreign_key_to_application_materials

Revision ID: 4867a7dc9b30
Revises: c7910d98c1d4
Create Date: 2026-01-29 23:51:09.292671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4867a7dc9b30'
down_revision: Union[str, Sequence[str], None] = 'c7910d98c1d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'application_materials', 'materials', ['material_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application_materials', type_='foreignkey')
    # ### end Alembic commands ###
