"""add_detailed_design_estimate_to_document_type

Revision ID: 4de91c5523d3
Revises: 79873b021cfb
Create Date: 2026-07-04 22:08:23.685519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4de91c5523d3'
down_revision: Union[str, Sequence[str], None] = '79873b021cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")
    op.execute("ALTER TYPE applicationdocumenttype ADD VALUE IF NOT EXISTS 'DETAILED_DESIGN_ESTIMATE'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
