"""add_application_objections_table

Revision ID: 50ce99150406
Revises: a1b2c3d4e5f6
Create Date: 2026-07-19 19:41:54.583871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50ce99150406'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    """Upgrade schema."""
    userrole_enum = postgresql.ENUM('SUPERADMIN', 'ADMIN', 'NODAL_OFFICER', 'COMMISSIONER', 'CITIZEN', 'NAKA_INCHARGE', 'DEPT_LAND', 'DEPT_LEGAL', 'DEPT_ATP', 'JEN', 'AEN', 'RIN', 'SIN', 'COLLECTOR', name='userrole', create_type=False)
    objectionstatus_enum = sa.Enum('PENDING', 'RESOLVED', name='objectionstatus')

    op.create_table('application_objections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('objected_by_id', sa.Integer(), nullable=False),
    sa.Column('objected_by_role', userrole_enum, nullable=False),
    sa.Column('objected_to_role', userrole_enum, nullable=False),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('reverted_document_url', sa.String(), nullable=True),
    sa.Column('status', objectionstatus_enum, nullable=False, server_default='PENDING'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_by_role', userrole_enum, nullable=True),
    sa.Column('resolution_remarks', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['objected_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_objections_application_id'), 'application_objections', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_objections_created_at'), 'application_objections', ['created_at'], unique=False)
    op.create_index(op.f('ix_application_objections_id'), 'application_objections', ['id'], unique=False)
    op.create_index(op.f('ix_application_objections_objected_by_id'), 'application_objections', ['objected_by_id'], unique=False)
    op.create_index(op.f('ix_application_objections_objected_by_role'), 'application_objections', ['objected_by_role'], unique=False)
    op.create_index(op.f('ix_application_objections_objected_to_role'), 'application_objections', ['objected_to_role'], unique=False)
    op.create_index(op.f('ix_application_objections_status'), 'application_objections', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_objections_status'), table_name='application_objections')
    op.drop_index(op.f('ix_application_objections_objected_to_role'), table_name='application_objections')
    op.drop_index(op.f('ix_application_objections_objected_by_role'), table_name='application_objections')
    op.drop_index(op.f('ix_application_objections_objected_by_id'), table_name='application_objections')
    op.drop_index(op.f('ix_application_objections_id'), table_name='application_objections')
    op.drop_index(op.f('ix_application_objections_created_at'), table_name='application_objections')
    op.drop_index(op.f('ix_application_objections_application_id'), table_name='application_objections')
    op.drop_table('application_objections')
    # ### end Alembic commands ###
