"""add_vehicle_type_location

Revision ID: 65bf1a846287
Revises: 32f70822c006
Create Date: 2026-04-21 12:11:04.095641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65bf1a846287'
down_revision: Union[str, Sequence[str], None] = '32f70822c006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_entries', sa.Column('vehicle_type', sa.String(), nullable=True))
    op.add_column('vehicle_entries', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('vehicle_entries', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_entries', 'longitude')
    op.drop_column('vehicle_entries', 'latitude')
    op.drop_column('vehicle_entries', 'vehicle_type')
    # ### end Alembic commands ###
