"""add_objection_comment_type

Revision ID: 66a3a8b9223b
Revises: 849ebac5adb7
Create Date: 2026-02-25 22:01:33.593160

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "66a3a8b9223b"
down_revision: Union[str, Sequence[str], None] = "849ebac5adb7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text("ALTER TYPE commenttype ADD VALUE IF NOT EXISTS 'OBJECTION_COMMENT'")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
