"""add_organization_name_to_application

Revision ID: 79873b021cfb
Revises: b2791e48392c
Create Date: 2026-07-04 22:02:40.284473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79873b021cfb'
down_revision: Union[str, Sequence[str], None] = 'b2791e48392c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('organization_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_applications_organization_name'), 'applications', ['organization_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_organization_name'), table_name='applications')
    op.drop_column('applications', 'organization_name')
    # ### end Alembic commands ###
