"""add_created_at_to_applications

Revision ID: 7e0469837c7f
Revises: cb5ecb4e393f
Create Date: 2026-04-07 20:24:17.638648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e0469837c7f'
down_revision: Union[str, Sequence[str], None] = 'cb5ecb4e393f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'created_at')
    # ### end Alembic commands ###
