"""add_vehicle_entry_dumping_photos

Revision ID: 917c2741a3d7
Revises: d87b441f258e
Create Date: 2026-04-20 12:07:25.265258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '917c2741a3d7'
down_revision: Union[str, Sequence[str], None] = 'd87b441f258e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_entry_dumping_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_entry_id', sa.Integer(), nullable=False),
    sa.Column('photo_path', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_entry_id'], ['vehicle_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_entry_dumping_photos_id'), 'vehicle_entry_dumping_photos', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_entry_dumping_photos_uploaded_at'), 'vehicle_entry_dumping_photos', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_vehicle_entry_dumping_photos_vehicle_entry_id'), 'vehicle_entry_dumping_photos', ['vehicle_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_entry_dumping_photos_vehicle_entry_id'), table_name='vehicle_entry_dumping_photos')
    op.drop_index(op.f('ix_vehicle_entry_dumping_photos_uploaded_at'), table_name='vehicle_entry_dumping_photos')
    op.drop_index(op.f('ix_vehicle_entry_dumping_photos_id'), table_name='vehicle_entry_dumping_photos')
    op.drop_table('vehicle_entry_dumping_photos')
    # ### end Alembic commands ###
