"""Initial_tables

Revision ID: 972d1dba2325
Revises:
Create Date: 2026-01-28 16:46:36.455618

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "972d1dba2325"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "active_user_otps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mobile", sa.String(), nullable=False),
        sa.Column("otp", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("valid_till", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_active_user_otps_id"), "active_user_otps", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_active_user_otps_mobile"), "active_user_otps", ["mobile"], unique=False
    )
    op.create_index(
        op.f("ix_active_user_otps_otp"), "active_user_otps", ["otp"], unique=False
    )
    op.create_table(
        "materials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("unit", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_materials_id"), "materials", ["id"], unique=False)
    op.create_index(op.f("ix_materials_name"), "materials", ["name"], unique=False)
    op.create_index(op.f("ix_materials_unit"), "materials", ["unit"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "SUPERADMIN",
                "COMMISSIONER",
                "CITIZEN",
                "NAKA_INCHARGE",
                "DEPT_LAND",
                "DEPT_LEGAL",
                "DEPT_ATP",
                "JEN",
                name="userrole",
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("mobile", sa.String(length=10), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_mobile"), "users", ["mobile"], unique=False)
    op.create_index(op.f("ix_users_name"), "users", ["name"], unique=False)
    op.create_index(op.f("ix_users_password"), "users", ["password"], unique=False)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=False)
    op.create_table(
        "applications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "APPROVED", "WITHHELD", "REJECTED", name="applicationstatus"
            ),
            nullable=False,
        ),
        sa.Column(
            "type", sa.Enum("NEW", "RENOVATION", name="applicationtype"), nullable=False
        ),
        sa.Column("num_stages", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_applications_id"), "applications", ["id"], unique=False)
    op.create_index(
        op.f("ix_applications_status"), "applications", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_applications_type"), "applications", ["type"], unique=False
    )
    op.create_index(
        op.f("ix_applications_user_id"), "applications", ["user_id"], unique=False
    )
    op.create_table(
        "application_approvals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("phase", sa.Integer(), nullable=True),
        sa.Column("approved_by", sa.Integer(), nullable=False),
        sa.Column("approved_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_approvals_application_id"),
        "application_approvals",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_approvals_approved_at"),
        "application_approvals",
        ["approved_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_approvals_approved_by"),
        "application_approvals",
        ["approved_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_approvals_id"),
        "application_approvals",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_approvals_phase"),
        "application_approvals",
        ["phase"],
        unique=False,
    )
    op.create_table(
        "application_comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("comment", sa.String(), nullable=False),
        sa.Column("comment_by", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["comment_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_comments_application_id"),
        "application_comments",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_comments_comment"),
        "application_comments",
        ["comment"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_comments_comment_by"),
        "application_comments",
        ["comment_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_comments_id"), "application_comments", ["id"], unique=False
    )
    op.create_table(
        "application_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column(
            "document_type",
            sa.Enum(
                "APPLICATION", "INSPECTION", "OTHER", name="applicationdocumenttype"
            ),
            nullable=False,
        ),
        sa.Column("document_name", sa.String(), nullable=True),
        sa.Column("document_path", sa.String(), nullable=False),
        sa.Column("document_by", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_documents_application_id"),
        "application_documents",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_documents_document_type"),
        "application_documents",
        ["document_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_documents_id"),
        "application_documents",
        ["id"],
        unique=False,
    )
    op.create_table(
        "application_materials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_materials_application_id"),
        "application_materials",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_materials_id"),
        "application_materials",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_materials_material_id"),
        "application_materials",
        ["material_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_materials_quantity"),
        "application_materials",
        ["quantity"],
        unique=False,
    )
    op.create_table(
        "application_phase_materials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("phase", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_phase_materials_application_id"),
        "application_phase_materials",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_phase_materials_id"),
        "application_phase_materials",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_phase_materials_material_id"),
        "application_phase_materials",
        ["material_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_phase_materials_phase"),
        "application_phase_materials",
        ["phase"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_phase_materials_quantity"),
        "application_phase_materials",
        ["quantity"],
        unique=False,
    )
    op.create_table(
        "application_phases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("phase", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "IN_PROGRESS",
                "COMPLETED",
                name="applicationphasestatus",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_phases_application_id"),
        "application_phases",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_phases_id"), "application_phases", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_application_phases_phase"),
        "application_phases",
        ["phase"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_phases_status"),
        "application_phases",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_application_phases_status"), table_name="application_phases")
    op.drop_index(op.f("ix_application_phases_phase"), table_name="application_phases")
    op.drop_index(op.f("ix_application_phases_id"), table_name="application_phases")
    op.drop_index(
        op.f("ix_application_phases_application_id"), table_name="application_phases"
    )
    op.drop_table("application_phases")
    op.drop_index(
        op.f("ix_application_phase_materials_quantity"),
        table_name="application_phase_materials",
    )
    op.drop_index(
        op.f("ix_application_phase_materials_phase"),
        table_name="application_phase_materials",
    )
    op.drop_index(
        op.f("ix_application_phase_materials_material_id"),
        table_name="application_phase_materials",
    )
    op.drop_index(
        op.f("ix_application_phase_materials_id"),
        table_name="application_phase_materials",
    )
    op.drop_index(
        op.f("ix_application_phase_materials_application_id"),
        table_name="application_phase_materials",
    )
    op.drop_table("application_phase_materials")
    op.drop_index(
        op.f("ix_application_materials_quantity"), table_name="application_materials"
    )
    op.drop_index(
        op.f("ix_application_materials_material_id"), table_name="application_materials"
    )
    op.drop_index(
        op.f("ix_application_materials_id"), table_name="application_materials"
    )
    op.drop_index(
        op.f("ix_application_materials_application_id"),
        table_name="application_materials",
    )
    op.drop_table("application_materials")
    op.drop_index(
        op.f("ix_application_documents_id"), table_name="application_documents"
    )
    op.drop_index(
        op.f("ix_application_documents_document_type"),
        table_name="application_documents",
    )
    op.drop_index(
        op.f("ix_application_documents_application_id"),
        table_name="application_documents",
    )
    op.drop_table("application_documents")
    op.drop_index(op.f("ix_application_comments_id"), table_name="application_comments")
    op.drop_index(
        op.f("ix_application_comments_comment_by"), table_name="application_comments"
    )
    op.drop_index(
        op.f("ix_application_comments_comment"), table_name="application_comments"
    )
    op.drop_index(
        op.f("ix_application_comments_application_id"),
        table_name="application_comments",
    )
    op.drop_table("application_comments")
    op.drop_index(
        op.f("ix_application_approvals_phase"), table_name="application_approvals"
    )
    op.drop_index(
        op.f("ix_application_approvals_id"), table_name="application_approvals"
    )
    op.drop_index(
        op.f("ix_application_approvals_approved_by"), table_name="application_approvals"
    )
    op.drop_index(
        op.f("ix_application_approvals_approved_at"), table_name="application_approvals"
    )
    op.drop_index(
        op.f("ix_application_approvals_application_id"),
        table_name="application_approvals",
    )
    op.drop_table("application_approvals")
    op.drop_index(op.f("ix_applications_user_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_type"), table_name="applications")
    op.drop_index(op.f("ix_applications_status"), table_name="applications")
    op.drop_index(op.f("ix_applications_id"), table_name="applications")
    op.drop_table("applications")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_password"), table_name="users")
    op.drop_index(op.f("ix_users_name"), table_name="users")
    op.drop_index(op.f("ix_users_mobile"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_materials_unit"), table_name="materials")
    op.drop_index(op.f("ix_materials_name"), table_name="materials")
    op.drop_index(op.f("ix_materials_id"), table_name="materials")
    op.drop_table("materials")
    op.drop_index(op.f("ix_active_user_otps_otp"), table_name="active_user_otps")
    op.drop_index(op.f("ix_active_user_otps_mobile"), table_name="active_user_otps")
    op.drop_index(op.f("ix_active_user_otps_id"), table_name="active_user_otps")
    op.drop_table("active_user_otps")
    # ### end Alembic commands ###
