"""add_government_to_property_usage

Revision ID: b2791e48392c
Revises: ec1033d83e27
Create Date: 2026-07-02 18:09:09.479648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2791e48392c'
down_revision: Union[str, Sequence[str], None] = 'ec1033d83e27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")
    op.execute("ALTER TYPE propertyusagetype ADD VALUE IF NOT EXISTS 'GOVERNMENT'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
