"""add_objected_from_status

Revision ID: bab3282aa849
Revises: c2d0017ff2fa
Create Date: 2026-07-16 21:17:21.334061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bab3282aa849'
down_revision: Union[str, Sequence[str], None] = 'c2d0017ff2fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE workflowaction ADD VALUE IF NOT EXISTS 'CLEAR_OBJECTION'")
    op.add_column('applications', sa.Column('objected_from_status', sa.Enum('PENDING', 'SUBMITTED', 'APPROVED', 'FORWARDED', 'WITHHELD', 'OBJECTED', 'REJECTED', 'TOKEN_GENERATED', 'WITHDRAWN', name='applicationstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'objected_from_status')
    # ### end Alembic commands ###
