"""add slot blackout calendar applicable days and grace period

Revision ID: beba142ecd78
Revises: c3228ca16908
Create Date: 2026-09-01 23:18:30.641289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beba142ecd78'
down_revision: Union[str, Sequence[str], None] = 'c3228ca16908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_blackouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blackout_date', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('is_full_day', sa.Boolean(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['slot_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_blackouts_blackout_date'), 'schedule_blackouts', ['blackout_date'], unique=False)
    op.create_index(op.f('ix_schedule_blackouts_id'), 'schedule_blackouts', ['id'], unique=False)
    op.add_column('slot_definitions', sa.Column('applicable_days', sa.String(), server_default='MON,TUE,WED,THU,FRI,SAT,SUN', nullable=False))
    op.add_column('slot_definitions', sa.Column('grace_period_minutes', sa.Integer(), server_default='30', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slot_definitions', 'grace_period_minutes')
    op.drop_column('slot_definitions', 'applicable_days')
    op.drop_index(op.f('ix_schedule_blackouts_id'), table_name='schedule_blackouts')
    op.drop_index(op.f('ix_schedule_blackouts_blackout_date'), table_name='schedule_blackouts')
    op.drop_table('schedule_blackouts')
    # ### end Alembic commands ###
