"""add_objection_to_role

Revision ID: c2d0017ff2fa
Revises: 4de91c5523d3
Create Date: 2026-07-15 22:38:40.355827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2d0017ff2fa'
down_revision: Union[str, Sequence[str], None] = '4de91c5523d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('objection_to_role', sa.Enum('SUPERADMIN', 'ADMIN', 'NODAL_OFFICER', 'COMMISSIONER', 'CITIZEN', 'NAKA_INCHARGE', 'DEPT_LAND', 'DEPT_LEGAL', 'DEPT_ATP', 'JEN', 'AEN', 'RIN', 'SIN', name='userrole'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'objection_to_role')
    # ### end Alembic commands ###
