"""add vehicle scheduling and slots

Revision ID: c3228ca16908
Revises: de5ad11363cd
Create Date: 2026-09-01 22:25:55.904659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'c3228ca16908'
down_revision: Union[str, Sequence[str], None] = 'de5ad11363cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slot_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slot_definitions_id'), 'slot_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_slot_definitions_name'), 'slot_definitions', ['name'], unique=False)
    op.create_table('vehicle_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_types_code'), 'vehicle_types', ['code'], unique=True)
    op.create_index(op.f('ix_vehicle_types_id'), 'vehicle_types', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_types_name'), 'vehicle_types', ['name'], unique=False)
    op.create_table('vehicle_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_code', sa.String(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('schedule_date', sa.DateTime(), nullable=False),
    sa.Column('vehicle_number', sa.String(), nullable=False),
    sa.Column('vehicle_type_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', 'EXPIRED', name='vehicleschedulestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['slot_definitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_schedules_application_id'), 'vehicle_schedules', ['application_id'], unique=False)
    op.create_index(op.f('ix_vehicle_schedules_id'), 'vehicle_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_schedules_phase'), 'vehicle_schedules', ['phase'], unique=False)
    op.create_index(op.f('ix_vehicle_schedules_schedule_code'), 'vehicle_schedules', ['schedule_code'], unique=True)
    op.create_index(op.f('ix_vehicle_schedules_schedule_date'), 'vehicle_schedules', ['schedule_date'], unique=False)
    op.create_index(op.f('ix_vehicle_schedules_slot_id'), 'vehicle_schedules', ['slot_id'], unique=False)
    op.create_index(op.f('ix_vehicle_schedules_status'), 'vehicle_schedules', ['status'], unique=False)
    op.create_index(op.f('ix_vehicle_schedules_user_id'), 'vehicle_schedules', ['user_id'], unique=False)
    op.create_index(op.f('ix_vehicle_schedules_vehicle_number'), 'vehicle_schedules', ['vehicle_number'], unique=False)

    compliance_status_enum = postgresql.ENUM('ON_TIME', 'SLOT_MISMATCH', 'UNSCHEDULED_WALK_IN', name='schedulecompliancestatus')
    compliance_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('vehicle_entries', sa.Column('schedule_id', sa.Integer(), nullable=True))
    op.add_column('vehicle_entries', sa.Column('schedule_compliance_status', compliance_status_enum, nullable=True))
    op.create_index(op.f('ix_vehicle_entries_schedule_id'), 'vehicle_entries', ['schedule_id'], unique=False)
    op.create_foreign_key(None, 'vehicle_entries', 'vehicle_schedules', ['schedule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicle_entries', type_='foreignkey')
    op.drop_index(op.f('ix_vehicle_entries_schedule_id'), table_name='vehicle_entries')
    op.drop_column('vehicle_entries', 'schedule_compliance_status')
    op.drop_column('vehicle_entries', 'schedule_id')
    op.drop_index(op.f('ix_vehicle_schedules_vehicle_number'), table_name='vehicle_schedules')
    op.drop_index(op.f('ix_vehicle_schedules_user_id'), table_name='vehicle_schedules')
    op.drop_index(op.f('ix_vehicle_schedules_status'), table_name='vehicle_schedules')
    op.drop_index(op.f('ix_vehicle_schedules_slot_id'), table_name='vehicle_schedules')
    op.drop_index(op.f('ix_vehicle_schedules_schedule_date'), table_name='vehicle_schedules')
    op.drop_index(op.f('ix_vehicle_schedules_schedule_code'), table_name='vehicle_schedules')
    op.drop_index(op.f('ix_vehicle_schedules_phase'), table_name='vehicle_schedules')
    op.drop_index(op.f('ix_vehicle_schedules_id'), table_name='vehicle_schedules')
    op.drop_index(op.f('ix_vehicle_schedules_application_id'), table_name='vehicle_schedules')
    op.drop_table('vehicle_schedules')
    op.drop_index(op.f('ix_vehicle_types_name'), table_name='vehicle_types')
    op.drop_index(op.f('ix_vehicle_types_id'), table_name='vehicle_types')
    op.drop_index(op.f('ix_vehicle_types_code'), table_name='vehicle_types')
    op.drop_table('vehicle_types')
    op.drop_index(op.f('ix_slot_definitions_name'), table_name='slot_definitions')
    op.drop_index(op.f('ix_slot_definitions_id'), table_name='slot_definitions')
    op.drop_table('slot_definitions')
    # ### end Alembic commands ###
