"""add_title_description_to_applications

Revision ID: c7910d98c1d4
Revises: 972d1dba2325
Create Date: 2026-01-29 23:32:05.470046

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c7910d98c1d4"
down_revision: Union[str, Sequence[str], None] = "972d1dba2325"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First add title as nullable to avoid issues with existing data
    op.add_column("applications", sa.Column("title", sa.String(), nullable=True))
    op.add_column("applications", sa.Column("description", sa.String(), nullable=True))

    # Set default value for existing rows
    op.execute(
        "UPDATE applications SET title = 'Untitled Application' WHERE title IS NULL"
    )

    # Now make title non-nullable
    op.alter_column("applications", "title", nullable=False)

    op.create_index(
        op.f("ix_applications_title"), "applications", ["title"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_applications_title"), table_name="applications")
    op.drop_column("applications", "description")
    op.drop_column("applications", "title")
    # ### end Alembic commands ###
