"""reinit

Revision ID: cb513640f036
Revises:
Create Date: 2026-02-10 21:36:23.919047

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cb513640f036"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "active_user_otps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mobile", sa.String(), nullable=False),
        sa.Column("otp", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("valid_till", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_active_user_otps_id"), "active_user_otps", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_active_user_otps_mobile"), "active_user_otps", ["mobile"], unique=False
    )
    op.create_index(
        op.f("ix_active_user_otps_otp"), "active_user_otps", ["otp"], unique=False
    )
    op.create_table(
        "complaint_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_complaint_categories_id"), "complaint_categories", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_complaint_categories_name"),
        "complaint_categories",
        ["name"],
        unique=False,
    )
    op.create_table(
        "departments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_departments_code"), "departments", ["code"], unique=True)
    op.create_index(op.f("ix_departments_id"), "departments", ["id"], unique=False)
    op.create_index(op.f("ix_departments_name"), "departments", ["name"], unique=False)
    op.create_table(
        "materials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("unit", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_materials_id"), "materials", ["id"], unique=False)
    op.create_index(op.f("ix_materials_name"), "materials", ["name"], unique=False)
    op.create_index(op.f("ix_materials_unit"), "materials", ["unit"], unique=False)
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("permissions", sa.String(), nullable=True),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_code"), "roles", ["code"], unique=True)
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "SUPERADMIN",
                "NODAL_OFFICER",
                "COMMISSIONER",
                "CITIZEN",
                "NAKA_INCHARGE",
                "DEPT_LAND",
                "DEPT_LEGAL",
                "DEPT_ATP",
                "JEN",
                name="userrole",
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("mobile", sa.String(length=10), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_mobile"), "users", ["mobile"], unique=False)
    op.create_index(op.f("ix_users_name"), "users", ["name"], unique=False)
    op.create_index(op.f("ix_users_password"), "users", ["password"], unique=False)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=False)
    op.create_table(
        "wards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_wards_code"), "wards", ["code"], unique=True)
    op.create_index(op.f("ix_wards_id"), "wards", ["id"], unique=False)
    op.create_index(op.f("ix_wards_name"), "wards", ["name"], unique=False)
    op.create_table(
        "applications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("applicant_name", sa.String(), nullable=False),
        sa.Column("father_name", sa.String(), nullable=False),
        sa.Column("mobile", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("current_address", sa.String(), nullable=False),
        sa.Column("property_address", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("work_description", sa.String(), nullable=False),
        sa.Column("contractor_name", sa.String(), nullable=True),
        sa.Column("is_agriculture_land", sa.Boolean(), nullable=False),
        sa.Column(
            "property_usage",
            sa.Enum("DOMESTIC", "COMMERCIAL", "HOTEL", name="propertyusagetype"),
            nullable=False,
        ),
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.Column("ward_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SUBMITTED",
                "APPROVED",
                "WITHHELD",
                "OBJECTED",
                "REJECTED",
                name="applicationstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "type", sa.Enum("NEW", "RENOVATION", name="applicationtype"), nullable=False
        ),
        sa.Column("num_stages", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ward_id"],
            ["wards.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_applications_applicant_name"),
        "applications",
        ["applicant_name"],
        unique=False,
    )
    op.create_index(op.f("ix_applications_id"), "applications", ["id"], unique=False)
    op.create_index(
        op.f("ix_applications_mobile"), "applications", ["mobile"], unique=False
    )
    op.create_index(
        op.f("ix_applications_status"), "applications", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_applications_title"), "applications", ["title"], unique=False
    )
    op.create_index(
        op.f("ix_applications_type"), "applications", ["type"], unique=False
    )
    op.create_index(
        op.f("ix_applications_user_id"), "applications", ["user_id"], unique=False
    )
    op.create_table(
        "city_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("area_sq_km", sa.String(), nullable=True),
        sa.Column("no_of_wards", sa.Integer(), nullable=True),
        sa.Column("ward_boundaries", sa.String(), nullable=True),
        sa.Column("population_estimate", sa.Integer(), nullable=True),
        sa.Column("rental_properties_of_corporation", sa.Integer(), nullable=True),
        sa.Column("number_of_slums", sa.Integer(), nullable=True),
        sa.Column("solid_waste_per_day", sa.String(), nullable=True),
        sa.Column("street_light_poles", sa.Integer(), nullable=True),
        sa.Column("employees_in_board", sa.Integer(), nullable=True),
        sa.Column("households_residential", sa.Integer(), nullable=True),
        sa.Column("households_shops_offices", sa.Integer(), nullable=True),
        sa.Column("households_open_plots", sa.Integer(), nullable=True),
        sa.Column("birth_registration_per_year", sa.Integer(), nullable=True),
        sa.Column("birth_certificate_per_year", sa.Integer(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_city_profiles_id"), "city_profiles", ["id"], unique=False)
    op.create_table(
        "complaints",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("ward_id", sa.Integer(), nullable=True),
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "RESOLVED",
                "WITHHELD",
                "REJECTED",
                name="complaintstatus",
            ),
            nullable=False,
        ),
        sa.Column("applicant_name", sa.String(), nullable=False),
        sa.Column("applicant_mobile", sa.String(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("location_address", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["complaint_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ward_id"],
            ["wards.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_complaints_id"), "complaints", ["id"], unique=False)
    op.create_index(
        op.f("ix_complaints_status"), "complaints", ["status"], unique=False
    )
    op.create_index(op.f("ix_complaints_title"), "complaints", ["title"], unique=False)
    op.create_index(
        op.f("ix_complaints_user_id"), "complaints", ["user_id"], unique=False
    )
    op.create_table(
        "downloads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_title", sa.String(), nullable=False),
        sa.Column("document_type", sa.String(), nullable=True),
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", name="downloadstatus"),
            nullable=False,
        ),
        sa.Column("uploaded_by", sa.Integer(), nullable=True),
        sa.Column(
            "uploaded_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_downloads_department_id"), "downloads", ["department_id"], unique=False
    )
    op.create_index(
        op.f("ix_downloads_document_title"),
        "downloads",
        ["document_title"],
        unique=False,
    )
    op.create_index(
        op.f("ix_downloads_document_type"), "downloads", ["document_type"], unique=False
    )
    op.create_index(op.f("ix_downloads_id"), "downloads", ["id"], unique=False)
    op.create_index(op.f("ix_downloads_status"), "downloads", ["status"], unique=False)
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=True),
        sa.Column("date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("venue", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "EXPIRED", "CANCELLED", "CLOSED", name="eventstatus"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_events_event_type"), "events", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_events_id"), "events", ["id"], unique=False)
    op.create_index(op.f("ix_events_status"), "events", ["status"], unique=False)
    op.create_index(op.f("ix_events_title"), "events", ["title"], unique=False)
    op.create_table(
        "leaders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("designation", sa.String(), nullable=True),
        sa.Column("tenure_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenure_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "EXPIRED", "INACTIVE", name="leaderstatus"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_leaders_id"), "leaders", ["id"], unique=False)
    op.create_index(op.f("ix_leaders_name"), "leaders", ["name"], unique=False)
    op.create_index(op.f("ix_leaders_status"), "leaders", ["status"], unique=False)
    op.create_table(
        "notices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("notice_type", sa.String(), nullable=True),
        sa.Column("published_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_till", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "EXPIRED", "INACTIVE", name="noticestatus"),
            nullable=False,
        ),
        sa.Column(
            "visibility",
            sa.Enum("PUBLIC", "INTERNAL", name="noticevisibility"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notices_id"), "notices", ["id"], unique=False)
    op.create_index(
        op.f("ix_notices_notice_type"), "notices", ["notice_type"], unique=False
    )
    op.create_index(op.f("ix_notices_status"), "notices", ["status"], unique=False)
    op.create_index(op.f("ix_notices_title"), "notices", ["title"], unique=False)
    op.create_index(
        op.f("ix_notices_visibility"), "notices", ["visibility"], unique=False
    )
    op.create_table(
        "tenders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("tender_type", sa.String(), nullable=True),
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("published_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submission_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "EXPIRED", "CANCELLED", "CLOSED", name="tenderstatus"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tenders_department_id"), "tenders", ["department_id"], unique=False
    )
    op.create_index(op.f("ix_tenders_id"), "tenders", ["id"], unique=False)
    op.create_index(op.f("ix_tenders_status"), "tenders", ["status"], unique=False)
    op.create_index(
        op.f("ix_tenders_tender_type"), "tenders", ["tender_type"], unique=False
    )
    op.create_index(op.f("ix_tenders_title"), "tenders", ["title"], unique=False)
    op.create_table(
        "application_approvals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("phase", sa.Integer(), nullable=True),
        sa.Column("approved_by", sa.Integer(), nullable=False),
        sa.Column("approved_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_approvals_application_id"),
        "application_approvals",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_approvals_approved_at"),
        "application_approvals",
        ["approved_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_approvals_approved_by"),
        "application_approvals",
        ["approved_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_approvals_id"),
        "application_approvals",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_approvals_phase"),
        "application_approvals",
        ["phase"],
        unique=False,
    )
    op.create_table(
        "application_comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("comment", sa.String(), nullable=False),
        sa.Column("comment_by", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["comment_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_comments_application_id"),
        "application_comments",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_comments_comment"),
        "application_comments",
        ["comment"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_comments_comment_by"),
        "application_comments",
        ["comment_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_comments_id"), "application_comments", ["id"], unique=False
    )
    op.create_table(
        "application_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column(
            "document_type",
            sa.Enum(
                "APPLICATION",
                "INSPECTION",
                "OTHER",
                "AADHAAR",
                "APPLICANT_PHOTO",
                "OWNERSHIP_DOCUMENTS",
                "PERMISSION_DOCUMENTS",
                "PROPERTY_PHOTOS",
                "SUPPORTING_DOCUMENTS",
                name="applicationdocumenttype",
            ),
            nullable=False,
        ),
        sa.Column("document_name", sa.String(), nullable=True),
        sa.Column("document_path", sa.String(), nullable=False),
        sa.Column("document_by", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_documents_application_id"),
        "application_documents",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_documents_document_type"),
        "application_documents",
        ["document_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_documents_id"),
        "application_documents",
        ["id"],
        unique=False,
    )
    op.create_table(
        "application_materials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_materials_application_id"),
        "application_materials",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_materials_id"),
        "application_materials",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_materials_material_id"),
        "application_materials",
        ["material_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_materials_quantity"),
        "application_materials",
        ["quantity"],
        unique=False,
    )
    op.create_table(
        "application_phase_materials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("phase", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_phase_materials_application_id"),
        "application_phase_materials",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_phase_materials_id"),
        "application_phase_materials",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_phase_materials_material_id"),
        "application_phase_materials",
        ["material_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_phase_materials_phase"),
        "application_phase_materials",
        ["phase"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_phase_materials_quantity"),
        "application_phase_materials",
        ["quantity"],
        unique=False,
    )
    op.create_table(
        "application_phases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("phase", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "WITHHELD",
                "REJECTED",
                "TERMINATED",
                "IN_PROGRESS",
                "COMPLETED",
                name="applicationphasestatus",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_phases_application_id"),
        "application_phases",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_phases_id"), "application_phases", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_application_phases_phase"),
        "application_phases",
        ["phase"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_phases_status"),
        "application_phases",
        ["status"],
        unique=False,
    )
    op.create_table(
        "complaint_comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("complaint_id", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("comment_by", sa.Integer(), nullable=True),
        sa.Column("media_path", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["comment_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["complaint_id"],
            ["complaints.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_complaint_comments_complaint_id"),
        "complaint_comments",
        ["complaint_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_complaint_comments_id"), "complaint_comments", ["id"], unique=False
    )
    op.create_table(
        "complaint_media",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("complaint_id", sa.Integer(), nullable=False),
        sa.Column("media_path", sa.String(), nullable=False),
        sa.Column("media_type", sa.String(), nullable=False),
        sa.Column("uploaded_by", sa.Integer(), nullable=True),
        sa.Column("is_initial", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["complaint_id"],
            ["complaints.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_complaint_media_complaint_id"),
        "complaint_media",
        ["complaint_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_complaint_media_id"), "complaint_media", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_complaint_media_id"), table_name="complaint_media")
    op.drop_index(op.f("ix_complaint_media_complaint_id"), table_name="complaint_media")
    op.drop_table("complaint_media")
    op.drop_index(op.f("ix_complaint_comments_id"), table_name="complaint_comments")
    op.drop_index(
        op.f("ix_complaint_comments_complaint_id"), table_name="complaint_comments"
    )
    op.drop_table("complaint_comments")
    op.drop_index(op.f("ix_application_phases_status"), table_name="application_phases")
    op.drop_index(op.f("ix_application_phases_phase"), table_name="application_phases")
    op.drop_index(op.f("ix_application_phases_id"), table_name="application_phases")
    op.drop_index(
        op.f("ix_application_phases_application_id"), table_name="application_phases"
    )
    op.drop_table("application_phases")
    op.drop_index(
        op.f("ix_application_phase_materials_quantity"),
        table_name="application_phase_materials",
    )
    op.drop_index(
        op.f("ix_application_phase_materials_phase"),
        table_name="application_phase_materials",
    )
    op.drop_index(
        op.f("ix_application_phase_materials_material_id"),
        table_name="application_phase_materials",
    )
    op.drop_index(
        op.f("ix_application_phase_materials_id"),
        table_name="application_phase_materials",
    )
    op.drop_index(
        op.f("ix_application_phase_materials_application_id"),
        table_name="application_phase_materials",
    )
    op.drop_table("application_phase_materials")
    op.drop_index(
        op.f("ix_application_materials_quantity"), table_name="application_materials"
    )
    op.drop_index(
        op.f("ix_application_materials_material_id"), table_name="application_materials"
    )
    op.drop_index(
        op.f("ix_application_materials_id"), table_name="application_materials"
    )
    op.drop_index(
        op.f("ix_application_materials_application_id"),
        table_name="application_materials",
    )
    op.drop_table("application_materials")
    op.drop_index(
        op.f("ix_application_documents_id"), table_name="application_documents"
    )
    op.drop_index(
        op.f("ix_application_documents_document_type"),
        table_name="application_documents",
    )
    op.drop_index(
        op.f("ix_application_documents_application_id"),
        table_name="application_documents",
    )
    op.drop_table("application_documents")
    op.drop_index(op.f("ix_application_comments_id"), table_name="application_comments")
    op.drop_index(
        op.f("ix_application_comments_comment_by"), table_name="application_comments"
    )
    op.drop_index(
        op.f("ix_application_comments_comment"), table_name="application_comments"
    )
    op.drop_index(
        op.f("ix_application_comments_application_id"),
        table_name="application_comments",
    )
    op.drop_table("application_comments")
    op.drop_index(
        op.f("ix_application_approvals_phase"), table_name="application_approvals"
    )
    op.drop_index(
        op.f("ix_application_approvals_id"), table_name="application_approvals"
    )
    op.drop_index(
        op.f("ix_application_approvals_approved_by"), table_name="application_approvals"
    )
    op.drop_index(
        op.f("ix_application_approvals_approved_at"), table_name="application_approvals"
    )
    op.drop_index(
        op.f("ix_application_approvals_application_id"),
        table_name="application_approvals",
    )
    op.drop_table("application_approvals")
    op.drop_index(op.f("ix_tenders_title"), table_name="tenders")
    op.drop_index(op.f("ix_tenders_tender_type"), table_name="tenders")
    op.drop_index(op.f("ix_tenders_status"), table_name="tenders")
    op.drop_index(op.f("ix_tenders_id"), table_name="tenders")
    op.drop_index(op.f("ix_tenders_department_id"), table_name="tenders")
    op.drop_table("tenders")
    op.drop_index(op.f("ix_notices_visibility"), table_name="notices")
    op.drop_index(op.f("ix_notices_title"), table_name="notices")
    op.drop_index(op.f("ix_notices_status"), table_name="notices")
    op.drop_index(op.f("ix_notices_notice_type"), table_name="notices")
    op.drop_index(op.f("ix_notices_id"), table_name="notices")
    op.drop_table("notices")
    op.drop_index(op.f("ix_leaders_status"), table_name="leaders")
    op.drop_index(op.f("ix_leaders_name"), table_name="leaders")
    op.drop_index(op.f("ix_leaders_id"), table_name="leaders")
    op.drop_table("leaders")
    op.drop_index(op.f("ix_events_title"), table_name="events")
    op.drop_index(op.f("ix_events_status"), table_name="events")
    op.drop_index(op.f("ix_events_id"), table_name="events")
    op.drop_index(op.f("ix_events_event_type"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_downloads_status"), table_name="downloads")
    op.drop_index(op.f("ix_downloads_id"), table_name="downloads")
    op.drop_index(op.f("ix_downloads_document_type"), table_name="downloads")
    op.drop_index(op.f("ix_downloads_document_title"), table_name="downloads")
    op.drop_index(op.f("ix_downloads_department_id"), table_name="downloads")
    op.drop_table("downloads")
    op.drop_index(op.f("ix_complaints_user_id"), table_name="complaints")
    op.drop_index(op.f("ix_complaints_title"), table_name="complaints")
    op.drop_index(op.f("ix_complaints_status"), table_name="complaints")
    op.drop_index(op.f("ix_complaints_id"), table_name="complaints")
    op.drop_table("complaints")
    op.drop_index(op.f("ix_city_profiles_id"), table_name="city_profiles")
    op.drop_table("city_profiles")
    op.drop_index(op.f("ix_applications_user_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_type"), table_name="applications")
    op.drop_index(op.f("ix_applications_title"), table_name="applications")
    op.drop_index(op.f("ix_applications_status"), table_name="applications")
    op.drop_index(op.f("ix_applications_mobile"), table_name="applications")
    op.drop_index(op.f("ix_applications_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_applicant_name"), table_name="applications")
    op.drop_table("applications")
    op.drop_index(op.f("ix_wards_name"), table_name="wards")
    op.drop_index(op.f("ix_wards_id"), table_name="wards")
    op.drop_index(op.f("ix_wards_code"), table_name="wards")
    op.drop_table("wards")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_password"), table_name="users")
    op.drop_index(op.f("ix_users_name"), table_name="users")
    op.drop_index(op.f("ix_users_mobile"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.drop_index(op.f("ix_roles_code"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_materials_unit"), table_name="materials")
    op.drop_index(op.f("ix_materials_name"), table_name="materials")
    op.drop_index(op.f("ix_materials_id"), table_name="materials")
    op.drop_table("materials")
    op.drop_index(op.f("ix_departments_name"), table_name="departments")
    op.drop_index(op.f("ix_departments_id"), table_name="departments")
    op.drop_index(op.f("ix_departments_code"), table_name="departments")
    op.drop_table("departments")
    op.drop_index(
        op.f("ix_complaint_categories_name"), table_name="complaint_categories"
    )
    op.drop_index(op.f("ix_complaint_categories_id"), table_name="complaint_categories")
    op.drop_table("complaint_categories")
    op.drop_index(op.f("ix_active_user_otps_otp"), table_name="active_user_otps")
    op.drop_index(op.f("ix_active_user_otps_mobile"), table_name="active_user_otps")
    op.drop_index(op.f("ix_active_user_otps_id"), table_name="active_user_otps")
    op.drop_table("active_user_otps")
    # ### end Alembic commands ###
