"""Remove department_id from complaints

Revision ID: cb5ecb4e393f
Revises: e4ca3088f9da
Create Date: 2026-03-03 19:04:12.850959

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cb5ecb4e393f"
down_revision: Union[str, Sequence[str], None] = "e4ca3088f9da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("complaints_department_id_fkey"), "complaints", type_="foreignkey"
    )
    op.drop_column("complaints", "department_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "complaints",
        sa.Column("department_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("complaints_department_id_fkey"),
        "complaints",
        "departments",
        ["department_id"],
        ["id"],
    )
    # ### end Alembic commands ###
