"""add_custom_material_fields

Revision ID: d87b441f258e
Revises: 3a3673c22af3
Create Date: 2026-04-17 00:27:51.204226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd87b441f258e'
down_revision: Union[str, Sequence[str], None] = '3a3673c22af3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_materials', sa.Column('custom_name', sa.String(), nullable=True))
    op.add_column('application_materials', sa.Column('custom_unit', sa.String(), nullable=True))
    op.alter_column('application_materials', 'material_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_check_constraint(
        "material_identity_check",
        "application_materials",
        "(material_id IS NOT NULL AND custom_name IS NULL AND custom_unit IS NULL) OR "
        "(material_id IS NULL AND custom_name IS NOT NULL AND custom_unit IS NOT NULL)"
    )

    op.add_column('application_phase_materials', sa.Column('custom_name', sa.String(), nullable=True))
    op.add_column('application_phase_materials', sa.Column('custom_unit', sa.String(), nullable=True))
    op.alter_column('application_phase_materials', 'material_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_check_constraint(
        "material_identity_check",
        "application_phase_materials",
        "(material_id IS NOT NULL AND custom_name IS NULL AND custom_unit IS NULL) OR "
        "(material_id IS NULL AND custom_name IS NOT NULL AND custom_unit IS NOT NULL)"
    )

    op.add_column('vehicle_materials', sa.Column('custom_name', sa.String(), nullable=True))
    op.add_column('vehicle_materials', sa.Column('custom_unit', sa.String(), nullable=True))
    op.alter_column('vehicle_materials', 'material_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_check_constraint(
        "material_identity_check",
        "vehicle_materials",
        "(material_id IS NOT NULL AND custom_name IS NULL AND custom_unit IS NULL) OR "
        "(material_id IS NULL AND custom_name IS NOT NULL AND custom_unit IS NOT NULL)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("material_identity_check", "vehicle_materials", type_="check")
    op.alter_column('vehicle_materials', 'material_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('vehicle_materials', 'custom_unit')
    op.drop_column('vehicle_materials', 'custom_name')

    op.drop_constraint("material_identity_check", "application_phase_materials", type_="check")
    op.alter_column('application_phase_materials', 'material_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('application_phase_materials', 'custom_unit')
    op.drop_column('application_phase_materials', 'custom_name')

    op.drop_constraint("material_identity_check", "application_materials", type_="check")
    op.alter_column('application_materials', 'material_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('application_materials', 'custom_unit')
    op.drop_column('application_materials', 'custom_name')
    # ### end Alembic commands ###
