"""add plaza_verified_at to vehicle_entries

Revision ID: de5ad11363cd
Revises: 50ce99150406
Create Date: 2026-08-23 22:21:44.487615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de5ad11363cd'
down_revision: Union[str, Sequence[str], None] = '50ce99150406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_objections', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('vehicle_entries', sa.Column('plaza_verified_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_vehicle_entries_plaza_verified_at'), 'vehicle_entries', ['plaza_verified_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_entries_plaza_verified_at'), table_name='vehicle_entries')
    op.drop_column('vehicle_entries', 'plaza_verified_at')
    op.alter_column('application_objections', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
