"""add created at and timestamp

Revision ID: df04cbaff05a
Revises: 3b2b4d33e972
Create Date: 2026-02-18 21:55:07.128553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df04cbaff05a'
down_revision: Union[str, Sequence[str], None] = '3b2b4d33e972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('vehicle_number', sa.String(), nullable=False),
    sa.Column('driver_name', sa.String(), nullable=True),
    sa.Column('driver_mobile', sa.String(), nullable=True),
    sa.Column('entry_by', sa.Integer(), nullable=False),
    sa.Column('entry_at', sa.DateTime(), nullable=False),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('media_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['entry_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_entries_application_id'), 'vehicle_entries', ['application_id'], unique=False)
    op.create_index(op.f('ix_vehicle_entries_entry_at'), 'vehicle_entries', ['entry_at'], unique=False)
    op.create_index(op.f('ix_vehicle_entries_entry_by'), 'vehicle_entries', ['entry_by'], unique=False)
    op.create_index(op.f('ix_vehicle_entries_id'), 'vehicle_entries', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_entries_phase'), 'vehicle_entries', ['phase'], unique=False)
    op.create_index(op.f('ix_vehicle_entries_vehicle_number'), 'vehicle_entries', ['vehicle_number'], unique=False)
    op.create_table('vehicle_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_entry_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['vehicle_entry_id'], ['vehicle_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_materials_id'), 'vehicle_materials', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_materials_material_id'), 'vehicle_materials', ['material_id'], unique=False)
    op.create_index(op.f('ix_vehicle_materials_vehicle_entry_id'), 'vehicle_materials', ['vehicle_entry_id'], unique=False)
    op.drop_index(op.f('ix_naka_entries_application_id'), table_name='naka_entries')
    op.drop_index(op.f('ix_naka_entries_entry_at'), table_name='naka_entries')
    op.drop_index(op.f('ix_naka_entries_entry_by'), table_name='naka_entries')
    op.drop_index(op.f('ix_naka_entries_id'), table_name='naka_entries')
    op.drop_index(op.f('ix_naka_entries_material_id'), table_name='naka_entries')
    op.drop_index(op.f('ix_naka_entries_phase'), table_name='naka_entries')
    op.drop_table('naka_entries')
    op.alter_column('application_approvals', 'action',
               existing_type=postgresql.ENUM('APPROVE', 'REJECT', 'OBJECT', 'FORWARD', 'GENERATE_TOKENS', name='workflowaction'),
               nullable=False)
    op.alter_column('application_comments', 'comment_type',
               existing_type=postgresql.ENUM('GENERAL', 'DEPT_REVIEW', 'OBJECTION_RESPONSE', 'INSPECTION_REMARK', name='commenttype'),
               nullable=False)
    op.alter_column('application_comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('complaint_categories', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('complaint_categories', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'complaint_categories', 'users', ['created_by_id'], ['id'])
    op.add_column('departments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('departments', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'departments', 'users', ['created_by_id'], ['id'])
    op.add_column('roles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('roles', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'roles', 'users', ['created_by_id'], ['id'])
    op.add_column('wards', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('wards', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wards', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wards', type_='foreignkey')
    op.drop_column('wards', 'created_by_id')
    op.drop_column('wards', 'created_at')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('roles', 'created_by_id')
    op.drop_column('roles', 'created_at')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'created_by_id')
    op.drop_column('departments', 'created_at')
    op.drop_constraint(None, 'complaint_categories', type_='foreignkey')
    op.drop_column('complaint_categories', 'created_by_id')
    op.drop_column('complaint_categories', 'created_at')
    op.alter_column('application_comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('application_comments', 'comment_type',
               existing_type=postgresql.ENUM('GENERAL', 'DEPT_REVIEW', 'OBJECTION_RESPONSE', 'INSPECTION_REMARK', name='commenttype'),
               nullable=True)
    op.alter_column('application_approvals', 'action',
               existing_type=postgresql.ENUM('APPROVE', 'REJECT', 'OBJECT', 'FORWARD', 'GENERATE_TOKENS', name='workflowaction'),
               nullable=True)
    op.create_table('naka_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('phase', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity_brought', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entry_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entry_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('vehicle_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('media_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('naka_entries_application_id_fkey')),
    sa.ForeignKeyConstraint(['entry_by'], ['users.id'], name=op.f('naka_entries_entry_by_fkey')),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('naka_entries_material_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('naka_entries_pkey'))
    )
    op.create_index(op.f('ix_naka_entries_phase'), 'naka_entries', ['phase'], unique=False)
    op.create_index(op.f('ix_naka_entries_material_id'), 'naka_entries', ['material_id'], unique=False)
    op.create_index(op.f('ix_naka_entries_id'), 'naka_entries', ['id'], unique=False)
    op.create_index(op.f('ix_naka_entries_entry_by'), 'naka_entries', ['entry_by'], unique=False)
    op.create_index(op.f('ix_naka_entries_entry_at'), 'naka_entries', ['entry_at'], unique=False)
    op.create_index(op.f('ix_naka_entries_application_id'), 'naka_entries', ['application_id'], unique=False)
    op.drop_index(op.f('ix_vehicle_materials_vehicle_entry_id'), table_name='vehicle_materials')
    op.drop_index(op.f('ix_vehicle_materials_material_id'), table_name='vehicle_materials')
    op.drop_index(op.f('ix_vehicle_materials_id'), table_name='vehicle_materials')
    op.drop_table('vehicle_materials')
    op.drop_index(op.f('ix_vehicle_entries_vehicle_number'), table_name='vehicle_entries')
    op.drop_index(op.f('ix_vehicle_entries_phase'), table_name='vehicle_entries')
    op.drop_index(op.f('ix_vehicle_entries_id'), table_name='vehicle_entries')
    op.drop_index(op.f('ix_vehicle_entries_entry_by'), table_name='vehicle_entries')
    op.drop_index(op.f('ix_vehicle_entries_entry_at'), table_name='vehicle_entries')
    op.drop_index(op.f('ix_vehicle_entries_application_id'), table_name='vehicle_entries')
    op.drop_table('vehicle_entries')
    # ### end Alembic commands ###
