"""Add department_id to complaint_categories

Revision ID: e4ca3088f9da
Revises: 0100b609ccb2
Create Date: 2026-03-03 17:02:39.678331

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e4ca3088f9da"
down_revision: Union[str, Sequence[str], None] = "0100b609ccb2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "complaint_categories", sa.Column("department_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "complaint_categories", "departments", ["department_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "complaint_categories", type_="foreignkey")
    op.drop_column("complaint_categories", "department_id")
    # ### end Alembic commands ###
