"""add created at and created by to materials

Revision ID: e7b8f9e1d2c3
Revises: 189f4d614d60
Create Date: 2026-02-21 06:25:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7b8f9e1d2c3"
down_revision: Union[str, Sequence[str], None] = "189f4d614d60"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("materials", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("materials", sa.Column("created_by_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "materials", "users", ["created_by_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "materials", type_="foreignkey")
    op.drop_column("materials", "created_by_id")
    op.drop_column("materials", "created_at")
    # ### end Alembic commands ###
