from enum import Enum as PyEnum


class UserRole(str, PyEnum):
    SUPERADMIN = "SUPERADMIN"
    CITIZEN = "CITIZEN"
    NAKA_INCHARGE = "NAKA_INCHARGE"
    DEPT_LAND = "DEPT_LAND"
    DEPT_ROAD = "DEPT_ROAD"
    DEPT_WATER = "DEPT_WATER"
    DEPT_ELECTRICITY = "DEPT_ELECTRICITY"
    DEPT_HEALTH = "DEPT_HEALTH"
    DEPT_EDUCATION = "DEPT_EDUCATION"
    DEPT_TRANSPORT = "DEPT_TRANSPORT"
    DEPT_OTHER = "DEPT_OTHER"
